"""LLM-based test generation from site crawl results.

Takes crawl data (site map, page elements, discovered flows) and generates:
1. Page Object Model (POM) classes for each discovered page
2. Test scripts grouped by user flow
3. All output written to tests/e2e/generated/ with metadata headers

Usage:
    from src.crawler.test_generator import CrawlTestGenerator

    generator = CrawlTestGenerator(crawl_results)
    generated_files = await generator.generate_all()
"""

import re
from datetime import datetime, timezone
from pathlib import Path

from src.agent.llm_provider import LLMProvider
from src.agent.prompts.site_analysis import build_site_analysis_prompt, format_pages_for_prompt
from src.agent.state import CrawlResults, PageNode, TestGenerationResult, TestScenario
from src.common.exceptions import LLMProviderError, LLMResponseParseError
from src.common.logging import get_logger

logger = get_logger(__name__)

# Base output directory for generated tests
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent / "tests" / "e2e" / "generated"

# Metadata header template for generated files
FILE_HEADER_TEMPLATE = '''"""
{description}

Auto-generated by QA Automation Agent
Generated: {timestamp}
Source URL: {source_url}
Page: {page_title} ({page_url})

DO NOT EDIT MANUALLY - This file will be regenerated on next crawl.
"""
'''


class CrawlTestGenerator:
    """Generates POM classes and test scripts from crawl results.

    Takes the structured output from the crawler (pages, elements, flows)
    and produces:
    - Page Object Model classes with selectors and action methods
    - Test scripts organized by user flow
    - All files have metadata headers for traceability
    """

    def __init__(
        self,
        crawl_results: CrawlResults,
        output_dir: str | Path | None = None,
    ) -> None:
        """Initialize the test generator.

        Args:
            crawl_results: Results from the site crawler.
            output_dir: Directory to write generated files.
                Defaults to tests/e2e/generated/.
        """
        self._crawl_results = crawl_results
        self._output_dir = Path(output_dir) if output_dir else DEFAULT_OUTPUT_DIR
        self._pom_dir = self._output_dir / "pages"
        self._tests_dir = self._output_dir / "tests"
        self._provider = LLMProvider()
        self._generated_files: list[str] = []

    async def generate_all(self) -> list[str]:
        """Generate all POM classes and test scripts from crawl results.

        Returns:
            List of file paths that were created.
        """
        self._generated_files.clear()

        # Ensure output directories exist
        self._pom_dir.mkdir(parents=True, exist_ok=True)
        self._tests_dir.mkdir(parents=True, exist_ok=True)

        # Write __init__.py files
        self._ensure_init_files()

        site_map = self._crawl_results.site_map

        logger.info(
            "crawl_test_generation_started",
            start_url=site_map.start_url,
            total_pages=site_map.total_pages,
            output_dir=str(self._output_dir),
        )

        # 1. Generate POM classes for each page with elements
        for page in site_map.pages:
            if page.elements:
                pom_path = await self._generate_pom_class(page)
                if pom_path:
                    self._generated_files.append(pom_path)

        # 2. Generate test scripts grouped by flow
        test_paths = await self._generate_test_scripts(site_map)
        self._generated_files.extend(test_paths)

        logger.info(
            "crawl_test_generation_completed",
            total_files=len(self._generated_files),
            pom_files=len([f for f in self._generated_files if "/pages/" in f]),
            test_files=len([f for f in self._generated_files if "/tests/" in f]),
        )

        return self._generated_files

    async def _generate_pom_class(self, page: PageNode) -> str | None:
        """Generate a Page Object Model class for a single page.

        Args:
            page: The PageNode with discovered elements.

        Returns:
            Path to the generated file, or None if generation failed.
        """
        class_name = self._url_to_class_name(page.url, page.title)
        file_name = self._url_to_file_name(page.url, page.title)

        # Build POM content from elements
        pom_content = self._build_pom_class(page, class_name)

        # Add metadata header
        header = FILE_HEADER_TEMPLATE.format(
            description=f"Page Object Model for: {page.title or page.url}",
            timestamp=datetime.now(timezone.utc).isoformat(),
            source_url=self._crawl_results.site_map.start_url,
            page_title=page.title or "Untitled",
            page_url=page.url,
        )

        full_content = header + pom_content

        # Write to file
        file_path = self._pom_dir / f"{file_name}_page.py"
        file_path.write_text(full_content, encoding="utf-8")

        logger.info(
            "pom_class_generated",
            class_name=class_name,
            file_path=str(file_path),
            elements_count=len(page.elements),
        )

        return str(file_path)

    def _build_pom_class(self, page: PageNode, class_name: str) -> str:
        """Build Python POM class content from page elements.

        Args:
            page: The PageNode with elements.
            class_name: Python class name for the POM.

        Returns:
            Python source code string for the POM class.
        """
        lines: list[str] = []

        lines.append("from playwright.sync_api import Page")
        lines.append("")
        lines.append("")
        lines.append(f"class {class_name}:")
        lines.append(f'    """Page Object Model for {page.title or page.url}."""')
        lines.append("")
        lines.append(f'    URL = "{page.url}"')
        lines.append("")

        # Selectors as class attributes
        lines.append("    # --- Selectors ---")
        selector_names: list[str] = []
        for elem in page.elements:
            attr_name = self._element_to_attr_name(elem)
            if attr_name and attr_name not in selector_names:
                selector_names.append(attr_name)
                lines.append(f'    {attr_name}_selector = "{elem.selector}"')

        lines.append("")

        # Constructor
        lines.append("    def __init__(self, page: Page) -> None:")
        lines.append('        """Initialize with a Playwright page instance."""')
        lines.append("        self.page = page")
        lines.append("")

        # Navigation method
        lines.append("    def navigate(self) -> None:")
        lines.append('        """Navigate to this page."""')
        lines.append(f'        self.page.goto("{page.url}")')
        lines.append('        self.page.wait_for_load_state("domcontentloaded")')
        lines.append("")

        # Action methods for buttons
        buttons = [e for e in page.elements if e.tag == "button"]
        for btn in buttons[:10]:  # Limit methods
            method_name = self._element_to_method_name(btn, "click")
            if method_name:
                lines.append(f"    def {method_name}(self) -> None:")
                btn_text = btn.text or btn.aria_label or "button"
                lines.append(f'        """Click the {btn_text} button."""')
                lines.append(f'        self.page.locator("{btn.selector}").click()')
                lines.append("")

        # Fill methods for inputs
        inputs = [e for e in page.elements if e.tag == "input" and e.element_type not in ("submit", "button", "reset")]
        for inp in inputs[:10]:  # Limit methods
            method_name = self._element_to_method_name(inp, "fill")
            if method_name:
                lines.append(f"    def {method_name}(self, value: str) -> None:")
                inp_label = inp.text or inp.aria_label or inp.element_type or "input"
                lines.append(f'        """Fill the {inp_label} field."""')
                lines.append(f'        self.page.locator("{inp.selector}").fill(value)')
                lines.append("")

        # Select methods for dropdowns
        selects = [e for e in page.elements if e.tag == "select"]
        for sel in selects[:5]:
            method_name = self._element_to_method_name(sel, "select")
            if method_name:
                lines.append(f"    def {method_name}(self, value: str) -> None:")
                sel_label = sel.text or sel.aria_label or "dropdown"
                lines.append(f'        """Select option in {sel_label}."""')
                lines.append(
                    f'        self.page.locator("{sel.selector}").select_option(value)'
                )
                lines.append("")

        # Assertion helpers
        lines.append("    def is_loaded(self) -> bool:")
        lines.append('        """Check if the page is fully loaded."""')
        lines.append("        try:")
        lines.append(f'            self.page.wait_for_url("**{self._url_path(page.url)}*")')
        lines.append("            return True")
        lines.append("        except Exception:")
        lines.append("            return False")
        lines.append("")

        return "\n".join(lines)

    async def _generate_test_scripts(self, site_map) -> list[str]:
        """Generate test scripts grouped by user flow.

        Creates separate test files for:
        - Navigation/smoke tests (all pages load)
        - Form interaction tests (pages with inputs)
        - Action/button tests (pages with buttons)
        - Flow-based tests (from suggested flows)

        Args:
            site_map: The discovered SiteMap.

        Returns:
            List of generated test file paths.
        """
        generated: list[str] = []

        # 1. Smoke test: all pages load correctly
        smoke_path = self._generate_smoke_tests(site_map)
        if smoke_path:
            generated.append(smoke_path)

        # 2. Form tests: pages with form elements
        form_pages = [p for p in site_map.pages if self._has_form_elements(p)]
        if form_pages:
            form_path = self._generate_form_tests(form_pages)
            if form_path:
                generated.append(form_path)

        # 3. Navigation tests: link connectivity
        if len(site_map.pages) > 1:
            nav_path = self._generate_navigation_tests(site_map)
            if nav_path:
                generated.append(nav_path)

        # 4. Action tests: button interactions
        action_pages = [p for p in site_map.pages if any(e.tag == "button" for e in p.elements)]
        if action_pages:
            action_path = self._generate_action_tests(action_pages)
            if action_path:
                generated.append(action_path)

        return generated

    def _generate_smoke_tests(self, site_map) -> str | None:
        """Generate smoke tests verifying all pages load.

        Args:
            site_map: The discovered SiteMap.

        Returns:
            Path to the generated file.
        """
        lines: list[str] = []

        header = FILE_HEADER_TEMPLATE.format(
            description="Smoke tests: verify all discovered pages load correctly",
            timestamp=datetime.now(timezone.utc).isoformat(),
            source_url=site_map.start_url,
            page_title="All Pages",
            page_url=site_map.start_url,
        )
        lines.append(header)
        lines.append("import allure")
        lines.append("import pytest")
        lines.append("from playwright.sync_api import Page")
        lines.append("")
        lines.append("")
        lines.append('@allure.feature("Smoke Tests")')
        lines.append('@allure.story("Page Load Verification")')
        lines.append("class TestSmokeGenerated:")
        lines.append('    """Auto-generated smoke tests for all discovered pages."""')
        lines.append("")

        for i, page in enumerate(site_map.pages):
            test_name = self._url_to_test_name(page.url, page.title)
            lines.append(f"    @allure.title('{page.title or page.url}')")
            lines.append("    @pytest.mark.smoke")
            lines.append(f"    def test_{test_name}_loads(self, page: Page) -> None:")
            lines.append(f'        """Verify {page.title or page.url} loads without errors."""')
            lines.append(f'        response = page.goto("{page.url}")')
            lines.append("        assert response is not None")
            lines.append("        assert response.status < 400, (")
            lines.append(f'            f"Page {page.url} returned status {{response.status}}"')
            lines.append("        )")
            title_check = page.title.replace('"', '\\"') if page.title else ""
            if title_check:
                lines.append(f'        assert "{title_check}" in page.title()')
            lines.append("")

        file_path = self._tests_dir / "test_smoke_generated.py"
        file_path.write_text("\n".join(lines), encoding="utf-8")
        return str(file_path)

    def _generate_form_tests(self, form_pages: list[PageNode]) -> str | None:
        """Generate tests for form interactions.

        Args:
            form_pages: Pages that contain form elements.

        Returns:
            Path to the generated file.
        """
        lines: list[str] = []

        header = FILE_HEADER_TEMPLATE.format(
            description="Form interaction tests for pages with input fields",
            timestamp=datetime.now(timezone.utc).isoformat(),
            source_url=self._crawl_results.site_map.start_url,
            page_title="Form Pages",
            page_url=self._crawl_results.site_map.start_url,
        )
        lines.append(header)
        lines.append("import allure")
        lines.append("import pytest")
        lines.append("from playwright.sync_api import Page")
        lines.append("")
        lines.append("")
        lines.append('@allure.feature("Form Tests")')
        lines.append('@allure.story("Form Interaction Verification")')
        lines.append("class TestFormsGenerated:")
        lines.append('    """Auto-generated tests for form elements on discovered pages."""')
        lines.append("")

        for page in form_pages:
            test_name = self._url_to_test_name(page.url, page.title)
            inputs = [e for e in page.elements if e.tag == "input" and e.element_type not in ("hidden", "submit", "button")]

            lines.append(f"    @allure.title('Form fields on {page.title or page.url}')")
            lines.append("    @pytest.mark.regression")
            lines.append(f"    def test_{test_name}_form_visible(self, page: Page) -> None:")
            lines.append(f'        """Verify form elements are visible on {page.title or page.url}."""')
            lines.append(f'        page.goto("{page.url}")')
            lines.append('        page.wait_for_load_state("domcontentloaded")')
            lines.append("")

            for inp in inputs[:5]:  # Limit assertions per page
                lines.append(f'        # Verify {inp.element_type or "input"} field: {inp.text or inp.selector}')
                lines.append(f'        locator = page.locator("{inp.selector}")')
                lines.append("        locator.wait_for(state='visible', timeout=5000)")
                lines.append("        assert locator.is_visible()")
                lines.append("")

            # Test form submission if there's a submit button
            submit_buttons = [e for e in page.elements if e.tag == "button" or (e.tag == "input" and e.element_type == "submit")]
            if submit_buttons and inputs:
                lines.append(f"    @allure.title('Form submission on {page.title or page.url}')")
                lines.append("    @pytest.mark.regression")
                lines.append(f"    def test_{test_name}_form_submit(self, page: Page) -> None:")
                lines.append(f'        """Test form submission with empty fields on {page.title or page.url}."""')
                lines.append(f'        page.goto("{page.url}")')
                lines.append('        page.wait_for_load_state("domcontentloaded")')
                lines.append("")
                btn = submit_buttons[0]
                lines.append(f'        # Click submit without filling fields')
                lines.append(f'        submit_btn = page.locator("{btn.selector}")')
                lines.append("        submit_btn.click()")
                lines.append("")
                lines.append("        # Verify validation feedback appears")
                lines.append('        # Note: specific validation selectors depend on the application')
                lines.append("        page.wait_for_timeout(1000)")
                lines.append("")

        file_path = self._tests_dir / "test_forms_generated.py"
        file_path.write_text("\n".join(lines), encoding="utf-8")
        return str(file_path)

    def _generate_navigation_tests(self, site_map) -> str | None:
        """Generate navigation flow tests.

        Args:
            site_map: The discovered SiteMap.

        Returns:
            Path to the generated file.
        """
        lines: list[str] = []

        header = FILE_HEADER_TEMPLATE.format(
            description="Navigation flow tests verifying page connectivity",
            timestamp=datetime.now(timezone.utc).isoformat(),
            source_url=site_map.start_url,
            page_title="Navigation",
            page_url=site_map.start_url,
        )
        lines.append(header)
        lines.append("import allure")
        lines.append("import pytest")
        lines.append("from playwright.sync_api import Page")
        lines.append("")
        lines.append("")
        lines.append('@allure.feature("Navigation Tests")')
        lines.append('@allure.story("Page Connectivity")')
        lines.append("class TestNavigationGenerated:")
        lines.append('    """Auto-generated navigation tests verifying link connectivity."""')
        lines.append("")

        # Test that starting page has working navigation
        lines.append("    @allure.title('Start page navigation links')")
        lines.append("    @pytest.mark.smoke")
        lines.append("    def test_start_page_navigation(self, page: Page) -> None:")
        lines.append(f'        """Verify navigation from the start page."""')
        lines.append(f'        page.goto("{site_map.start_url}")')
        lines.append('        page.wait_for_load_state("domcontentloaded")')
        lines.append("")
        lines.append("        # Verify navigation links are present")
        lines.append("        nav_links = page.locator('nav a, [role=\"navigation\"] a')")
        lines.append("        count = nav_links.count()")
        lines.append("        assert count > 0, 'Expected navigation links on start page'")
        lines.append("")

        # Test depth-1 pages are reachable from start
        depth_1_pages = [p for p in site_map.pages if p.depth == 1]
        if depth_1_pages:
            lines.append("    @allure.title('Direct child pages reachable')")
            lines.append("    @pytest.mark.regression")
            lines.append("    def test_depth_1_pages_reachable(self, page: Page) -> None:")
            lines.append('        """Verify pages at depth 1 are reachable from the start page."""')
            lines.append(f'        page.goto("{site_map.start_url}")')
            lines.append('        page.wait_for_load_state("domcontentloaded")')
            lines.append("")
            lines.append("        # Check that links to child pages exist")
            for child in depth_1_pages[:5]:
                path = self._url_path(child.url)
                lines.append(f'        link = page.locator(\'a[href*="{path}"]\')')
                lines.append(f"        # Link to {child.title or child.url}")
                lines.append("        if link.count() > 0:")
                lines.append("            assert link.first.is_visible()")
                lines.append("")

        # Test back navigation
        lines.append("    @allure.title('Browser back navigation works')")
        lines.append("    @pytest.mark.regression")
        lines.append("    def test_back_navigation(self, page: Page) -> None:")
        lines.append('        """Verify browser back button returns to previous page."""')
        lines.append(f'        page.goto("{site_map.start_url}")')
        lines.append('        page.wait_for_load_state("domcontentloaded")')
        lines.append("")
        if depth_1_pages:
            lines.append(f'        # Navigate to a child page')
            lines.append(f'        page.goto("{depth_1_pages[0].url}")')
            lines.append('        page.wait_for_load_state("domcontentloaded")')
        lines.append("")
        lines.append("        # Go back")
        lines.append("        page.go_back()")
        lines.append('        page.wait_for_load_state("domcontentloaded")')
        lines.append("")
        lines.append(f'        # Should be back at start')
        lines.append(f'        assert "{self._url_path(site_map.start_url)}" in page.url')
        lines.append("")

        file_path = self._tests_dir / "test_navigation_generated.py"
        file_path.write_text("\n".join(lines), encoding="utf-8")
        return str(file_path)

    def _generate_action_tests(self, action_pages: list[PageNode]) -> str | None:
        """Generate tests for button/action interactions.

        Args:
            action_pages: Pages with button elements.

        Returns:
            Path to the generated file.
        """
        lines: list[str] = []

        header = FILE_HEADER_TEMPLATE.format(
            description="Action/button interaction tests",
            timestamp=datetime.now(timezone.utc).isoformat(),
            source_url=self._crawl_results.site_map.start_url,
            page_title="Actions",
            page_url=self._crawl_results.site_map.start_url,
        )
        lines.append(header)
        lines.append("import allure")
        lines.append("import pytest")
        lines.append("from playwright.sync_api import Page")
        lines.append("")
        lines.append("")
        lines.append('@allure.feature("Action Tests")')
        lines.append('@allure.story("Button Interactions")')
        lines.append("class TestActionsGenerated:")
        lines.append('    """Auto-generated tests for button and action elements."""')
        lines.append("")

        for page in action_pages:
            test_name = self._url_to_test_name(page.url, page.title)
            buttons = [e for e in page.elements if e.tag == "button"]

            lines.append(f"    @allure.title('Buttons visible on {page.title or page.url}')")
            lines.append("    @pytest.mark.regression")
            lines.append(f"    def test_{test_name}_buttons_visible(self, page: Page) -> None:")
            lines.append(f'        """Verify action buttons are visible on {page.title or page.url}."""')
            lines.append(f'        page.goto("{page.url}")')
            lines.append('        page.wait_for_load_state("domcontentloaded")')
            lines.append("")

            for btn in buttons[:5]:
                btn_desc = btn.text or btn.aria_label or btn.selector
                lines.append(f'        # Button: {btn_desc}')
                lines.append(f'        btn = page.locator("{btn.selector}")')
                lines.append("        if btn.count() > 0:")
                lines.append("            assert btn.first.is_visible()")
                lines.append("            assert btn.first.is_enabled()")
                lines.append("")

        file_path = self._tests_dir / "test_actions_generated.py"
        file_path.write_text("\n".join(lines), encoding="utf-8")
        return str(file_path)

    # --- Utility Methods ---

    def _ensure_init_files(self) -> None:
        """Create __init__.py files in output directories."""
        for dir_path in (self._output_dir, self._pom_dir, self._tests_dir):
            init_file = dir_path / "__init__.py"
            if not init_file.exists():
                init_file.write_text("", encoding="utf-8")

    def _url_to_class_name(self, url: str, title: str = "") -> str:
        """Convert URL/title to a valid Python class name.

        Args:
            url: The page URL.
            title: Optional page title.

        Returns:
            PascalCase class name (e.g., LoginPage).
        """
        # Prefer title if available
        source = title if title else self._url_path(url)
        # Clean and convert to PascalCase
        cleaned = re.sub(r"[^\w\s]", " ", source)
        parts = cleaned.split()
        class_name = "".join(word.capitalize() for word in parts if word)
        if not class_name:
            class_name = "Unknown"
        return f"{class_name}Page"

    def _url_to_file_name(self, url: str, title: str = "") -> str:
        """Convert URL/title to a valid Python file name (snake_case).

        Args:
            url: The page URL.
            title: Optional page title.

        Returns:
            snake_case file name without extension.
        """
        source = title if title else self._url_path(url)
        cleaned = re.sub(r"[^\w\s]", " ", source).lower()
        parts = cleaned.split()
        file_name = "_".join(p for p in parts if p)
        return file_name or "unknown"

    def _url_to_test_name(self, url: str, title: str = "") -> str:
        """Convert URL/title to a valid pytest test function name.

        Uses the URL path to ensure uniqueness even when multiple pages
        share the same title. Falls back to title only for the root page.

        Args:
            url: The page URL.
            title: Optional page title.

        Returns:
            snake_case test name guaranteed unique per URL.
        """
        # Always derive from URL path for uniqueness
        path = self._url_path(url)
        if path and path != "/":
            # Use path: /catalogo?cat=Perros → catalogo_cat_perros
            cleaned = re.sub(r"[^\w\s]", " ", path).lower()
            parts = cleaned.split()
            name = "_".join(p for p in parts if p)
        elif title:
            # Root page: use title
            cleaned = re.sub(r"[^\w\s]", " ", title).lower()
            parts = cleaned.split()
            name = "_".join(p for p in parts if p)
        else:
            name = "home"

        # Ensure it starts with a letter
        if name and name[0].isdigit():
            name = f"page_{name}"
        return name or "unknown"

    def _element_to_attr_name(self, elem) -> str:
        """Convert an element to a Python attribute name.

        Args:
            elem: PageElement object.

        Returns:
            snake_case attribute name, or empty if cannot generate.
        """
        # Use text, aria-label, name, or type
        source = elem.text or elem.aria_label or ""
        if not source:
            # Try to extract from selector
            if "name='" in elem.selector:
                match = re.search(r"name='([^']+)'", elem.selector)
                if match:
                    source = match.group(1)
            elif "#" in elem.selector:
                source = elem.selector.lstrip("#")

        if not source:
            source = f"{elem.tag}_{elem.element_type}" if elem.element_type else elem.tag

        cleaned = re.sub(r"[^\w\s]", " ", source).lower().strip()
        parts = cleaned.split()[:4]  # Max 4 words
        name = "_".join(p for p in parts if p)
        return name or ""

    def _element_to_method_name(self, elem, prefix: str) -> str:
        """Convert an element to a Python method name.

        Args:
            elem: PageElement object.
            prefix: Method prefix (e.g., "click", "fill").

        Returns:
            snake_case method name, or empty if cannot generate.
        """
        attr_name = self._element_to_attr_name(elem)
        if not attr_name:
            return ""
        return f"{prefix}_{attr_name}"

    def _url_path(self, url: str) -> str:
        """Extract the path portion of a URL.

        Args:
            url: Full URL.

        Returns:
            The path component (e.g., "/login").
        """
        from urllib.parse import urlparse

        return urlparse(url).path or "/"

    @staticmethod
    def _has_form_elements(page: PageNode) -> bool:
        """Check if a page has form-related elements."""
        return any(
            e.tag in ("input", "textarea", "select")
            and e.element_type not in ("hidden", "submit", "button")
            for e in page.elements
        )
